databases:
  - name: optive
    databaseName: optive
    user: optive

services:
  - type: web
    name: optive
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: optive
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
